# my global config
global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['devops-backend-app.herokuapp.com']

#docker run -d -p 9090:9090 -v :/etc/prometheus/prometheus.yml prom/prometheus --config.file=/etc/prometheus/prometheus.yml